# Generated by Django 4.2.5 on 2023-09-25 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0002_rename_nome_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Controle.user'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='disciplinas',
            field=models.ManyToManyField(to='Controle.disciplina'),
        ),
    ]
