# Generated by Django 4.2.5 on 2023-09-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controle', '0003_rename_nome_aluno_name_remove_tarefa_concluida_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='TarefaDisciplina',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='Controle.user'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='disciplinas',
            field=models.ManyToManyField(related_name='Task', to='Controle.disciplina'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
